
# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
services: mongodb

scala:
  - 2.12.11
  - 2.13.1

branches:
  only:
    - master
notifications:
  email:
    recipients:
      - tom@sfxcode.com
jdk:
  - openjdk11
  - oraclejdk8

