
# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
services: mongodb

scala:
  - 2.12.11
  - 2.13.1

branches:
  only:
    - master
notifications:
  email:
    recipients:
      - tom@sfxcode.com
jdk:
  - openjdk11
  - openjdk8

before_script:
  - echo "replSet = myReplSetName" | sudo tee -a /etc/mongodb.conf
  - service mongodb restart
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 15

