name: Test Process

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.4', '5.0', '6.0', '7.0']
        java: [ '11', '17', '21' ]
    steps:
    - uses: actions/checkout@main
    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@main
      with:
        distribution: 'corretto'
        java-version: ${{ matrix.java }}
    - name: Setup TimeZone
      uses: szenius/set-timezone@master
      with:
        timezoneLinux: "Europe/Berlin"
        timezoneMacos: "Europe/Berlin"
        timezoneWindows: "W. Europe Standard Time"
    - name: Start MongoDB ${{ matrix.mongodb-version }}
      uses: MongoCamp/mongodb-github-action@main
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Run tests
      run: |
        timedatectl
        sbt +test